name: Pull Request Validation

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - main
    types:
      - merged

    paths-ignore:
      - .github
      - .vscode

  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  node-version: 18.18

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ env.node-version }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: npm

      - run: npm clean-install

      - run: npm run build --if-present
